---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: docker
    image: openmicroscopy/centos-systemd-ip:latest
    privileged: true
    command: /sbin/init
    ansible_groups:
      - docker-hosts
  - name: docker-inactive
    image: centos:7
    ansible_groups:
      - docker-hosts
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      docker-hosts:
        # This should allow docker-in-docker to work
        docker_storage_driver: vfs
    host_vars:
      docker:
        docker_use_ipv4_nic_mtu: true
        # Latest version 17.12.1.ce-1.el7.centos has a bug that prevents
        # testing on travis: https://github.com/docker/for-linux/issues/219
        docker_version: 17.09.1.ce-1.el7.centos
      docker-inactive:
        docker_systemd_setup: false
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
